#ifndef SRC_SHARED_GFX_GFXDEFINES_HPP
#define SRC_SHARED_GFX_GFXDEFINES_HPP

#define GFX_SUCCESS 0
#define GFX_FAILURE -1
//#define GFX_VIEWPORT_MAX 8
//#define GFX_MAX_COMMAND_SIZE 40000
//#define GFX_MAX_LIGHTS 4096
//#define GFX_LIGHTS_WORK_GROUP_SIZE 16
//#define GFX_HDR_BLOOM_DOWNSAMPLES 8

#define gfxBitMask unsigned long long


#endif